apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: connectk
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: connectk
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
