apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: connectk-ssd
  labels:
    app.kubernetes.io/part-of: connectk
# Azure Disk CSI driver (pre-installed on AKS 1.21+)
provisioner: disk.csi.azure.com
parameters:
  skuName: StandardSSD_LRS
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
